// Testbench for the PyRAL / UVM-agent register-access path.
//
// Structure:
//   - a clock and the APB3 bus
//   - the register block generated by peakrdl regblock (slave on APB)
//   - a uvm_test whose build_phase creates the reg_agent (so Python's
//     start_seq() can find its sequencer by path) and whose main_phase
//     hands control to Python via py_func
//
// The agent's driver is what actually performs the APB transfers; the
// Python side only stages an operation in the config_db and calls
// start_seq(), then reads the result back out of the same database.

module top;
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    import python_bridge_pkg::*;
    import reg_agent_pkg::*;
    import reg_seq_pkg::*;
    import demo_regs_pkg::*;

    localparam int ADDR_WIDTH = 32;
    localparam int DATA_WIDTH = 32;

    logic clk;
    logic rst;

    initial clk = 1'b0;
    always #5 clk = ~clk;

    initial begin
        rst = 1'b1;
        repeat (3) @(posedge clk);
        rst = 1'b0;
    end

    // APB bus. The generated block declares "apb3_intf.slave s_apb", so the
    // interface instance is connected through its slave modport.
    apb3_intf #(.DATA_WIDTH(DATA_WIDTH), .ADDR_WIDTH(ADDR_WIDTH)) m_apb (
        .clk(clk), .rst(rst)
    );

    // The register block's hw=w inputs. Tied off so the block is
    // deterministic; the registers themselves keep their own storage and
    // are what the test reads back.
    demo_regs__in_t  hwif_in;
    demo_regs__out_t hwif_out;

    // Assigned with '{default: 0} rather than a '0 fill. '0 is not portable
    // for an unpacked struct: verilator rejects it outright, and xezim
    // leaves the members at X. '{default: 0} is the standard zero fill for
    // an unpacked aggregate and both accept it.
    always_comb hwif_in = '{default: 0};

    demo_regs u_dut (
        .clk     (clk),
        .rst     (rst),
        .s_apb   (m_apb.slave),
        .hwif_in (hwif_in),
        .hwif_out(hwif_out)
    );

    // The APB master. It is an interface instance, elaborated here like the
    // register block is - the agent drives it through a virtual-interface
    // handle, so this is the only place it exists.
    apb3_intf_driver m_apb_bridge (
        .clk  (clk),
        .rst  (rst),
        .m_apb(m_apb)
    );

    // Make the bridge visible to the agent, which is created dynamically by
    // Python and therefore cannot reach the testbench hierarchy directly.
    // The bridge already holds the bus itself, through its m_apb port.
    initial
        uvm_config_db#(virtual apb3_intf_driver)::set(null, "*", "m_apb_drv", m_apb_bridge);

    class reg_test extends uvm_test;
        reg_agent m_agent;

        `uvm_component_utils(reg_test)

        function new(string name, uvm_component parent);
            super.new(name, parent);
        endfunction

        function void build_phase(uvm_phase phase);
            super.build_phase(phase);
            m_agent = reg_agent::type_id::create("m_agent", this);
        endfunction

        virtual task main_phase(uvm_phase phase);
            string py_dir;

            phase.raise_objection(this);

            if (!$value$plusargs("PY_DIR=%s", py_dir)) py_dir = "";
            py_task(get_type_name(), "main", py_dir);

            phase.drop_objection(this);
        endtask
    endclass

    initial begin
        run_test();
    end
endmodule
