'''svuvm'''
from . import config  # noqa: F401
try:
    from ._version import version as __version__  # noqa: F401
except ImportError:
    # Generated by setuptools_scm during build; absent only in raw checkouts
    __version__ = "0.0.0+unknown"
try:
    from ._svuvm import *  # type: ignore # noqa: F403
    from ._svuvm import vpi  # type: ignore # noqa: F401
except ImportError:
    pass
