#!/usr/bin/env python3
"""生成SV导出声明"""
import sys
from pathlib import Path
try:
    import pyslang
except ImportError:
    print("Error: pyslang is required. Install with: pip install pyslang")
    sys.exit(1)

exclude_func_list = [
    "py_func",
    "call_py_func",
    "get_contxt",
    "base16_encode",
    "base16_decode",
    "wait_trigger_data",
    "wait_ptrigger_data",
    "get_trigger_data",
    "get_default_data",
    "set_default_data",
    "set_config_int_array_t",
    "get_config_int_array_t",
    "set_config_byte_array_t",
    "get_config_byte_array_t",
]

def get_sv_export(filename = "src/svuvm/python_bridge_pkg.sv"):
    tree = pyslang.syntax.SyntaxTree.fromFile(filename)
    root = tree.root

    # 创建输出路径对象
    target_file = Path(filename)

    # 收集DPI-C导出声明
    output_lines = ["    // Generated by gen_export.py", "    // Do not edit this file manually"]
    for member in root.members[0].members:
        if member.kind == pyslang.syntax.SyntaxKind.TaskDeclaration:
            if member.prototype.name.identifier.value in exclude_func_list:
                continue
            output_lines.append(f'    export "DPI-C" task     {member.prototype.name};')
        elif member.kind == pyslang.syntax.SyntaxKind.FunctionDeclaration:
            if member.prototype.name.identifier.value in exclude_func_list:
                continue
            output_lines.append(f'    export "DPI-C" function {member.prototype.name};')

    # 读取原始文件内容
    if target_file.exists():
        content = target_file.read_text().splitlines()
    else:
        content = []

    # 查找标记位置
    begin_marker = "// EXPORT_DPIC_BEGIN"
    end_marker = "// EXPORT_DPIC_END"

    begin_idx = None
    end_idx = None

    for i, line in enumerate(content):
        if line.strip() == begin_marker:
            begin_idx = i
        elif line.strip() == end_marker:
            end_idx = i
            break

    # 替换标记之间内容
    if begin_idx is not None and end_idx is not None:
        # 保留标记前的内容 + 新生成内容 + 标记后的内容
        new_content = content[: begin_idx + 1] + output_lines + content[end_idx:]
    else:
        # 如果没有找到标记，则附加标记和内容
        new_content = content + [begin_marker] + output_lines + [end_marker]

    # 写回文件
    target_file.write_text("\n".join(new_content))


def get_cheader(filename = "src/svuvm/python_bridge_pkg.sv"):
    tree = pyslang.syntax.SyntaxTree.fromFile(filename)
    root = tree.root

    output_lines = ["    // Generated by gen_export.py", "    // Do not edit this file manually"]
    for member in root.members[0].members:
        if member.kind == pyslang.syntax.SyntaxKind.TaskDeclaration:
            if member.prototype.name.identifier.value in exclude_func_list:
                continue
            prototype = str(member.prototype)
            prototype = (
                prototype.replace("task automatic", "void")
                .replace("output string", "char **")
                .replace("string", "const char *")
                .replace("output int", "int *")
                .replace("uvm_action", "int")
                .replace("bit", "unsigned char")
                .replace("longint", "long long")
            )
            output_lines.append(f"{prototype};")
        elif member.kind == pyslang.syntax.SyntaxKind.FunctionDeclaration:
            if member.prototype.name.identifier.value in exclude_func_list:
                continue
            prototype = str(member.prototype)
            prototype = (
                prototype.replace("function automatic ", "")
                .replace("output string", "const char *")
                .replace("string", "const char *")
                .replace("output int", "int *")
                .replace("uvm_action", "int")
                .replace("bit", "unsigned char")
                .replace("longint", "long long")
                .replace("config_const char *", "config_string")
            )
            output_lines.append(f"{prototype};")

    (Path(__file__).parent.parent / "inc/export_dpi.h").write_text("".join(output_lines))

def main():
    get_sv_export(__file__.replace("scripts/generate_sv_export.py", "src/svuvm/python_bridge_pkg.sv"))
    get_cheader(__file__.replace("scripts/generate_sv_export.py", "src/svuvm/python_bridge_pkg.sv"))

if __name__ == "__main__":
    main()
