name: Test

on:
  push:
    branches: ["ccache-experiment"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: /home/runner/.ccache
      OBJCACHE: ccache
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Cache ccache
      uses: actions/cache@v6
      with:
        path: ~/.ccache
        key: ccache-ubuntu-${{ github.sha }}
        restore-keys: ccache-ubuntu-

    - name: Cache verilator (Ubuntu)
      uses: actions/cache@v6
      env:
        cache-name: cache-verilator-new
      with:
        path: /home/runner/work/verilator
        key: verilator-v5${{ env.cache-name }}

    - name: Install dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ccache help2man make g++ perl python3 autoconf flex bison libfl2 libfl-dev zlib1g zlib1g-dev
        ccache --set-config=max_size=1G
        ccache -z
        sudo bash ./script/install_verilator.sh

    - name: Clone verilator-uvm repository
      run: |
        git clone https://github.com/Dragon-Git/uvm-verilator.git

    - name: Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install . -v
        python -m pip install cocotb

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v4.1.0

    - name: Run base test
      run: |
        make -f test/base_test/Makefile run

    - name: Run cocotb test
      run: |
        make -f test/cocotb_test/Makefile run

    - name: ccache stats
      run: ccache -s
